### ISSUE TITLE
Clicks on labels do not work for friendly/enemy radio input

### ISSUE THREAD

**Issue by Loskir** [filecc/cooldown-calculator-ingress#1]
Now you can't change portal faction by clicking on the labels, only on the inputs itself.

One possible fix is to place inputs inside their labels:

```html
<label><input/>Friendly</label>
```

Another is to change `for` attributes to match the ids of the inputs (`friend` and `enemy` respectively)

**Comment by ynad** [comment]
> Now you can't change portal faction by clicking on the labels, only on the inputs itself.
> 
> One possible fix is to place inputs inside their labels:
> 
> ```
> <label><input/>Friendly</label>
> ```
> 
> Another is to change `for` attributes to match the ids of the inputs (`friend` and `enemy` respectively)

applied suggested edit on for attributes, now clicks on labels work too. Thanks for pointing it out! :D

**Comment by filecc** [comment]
Thanks you all ❤️
